-- lvl 4
CREATURE_TOUR_RIDER = CREATURE_GOBLIN
CREATURE_TOUR_CHAMPION = CREATURE_GOBLIN_TRAPPER
CREATURE_TOUR_EQUESTRIAN = CREATURE_GOBLIN_DEFILER

-- lvl 2
CREATURE_SHOOTER = CREATURE_CENTAUR
CREATURE_HUNTER = CREATURE_CENTAUR_NOMAD
CREATURE_GRENADIER = CREATURE_CENTAUR_MARADEUR

-- lvl 3
CREATURE_PIKEMAN = CREATURE_ORC_WARRIOR
CREATURE_DWARF_GUARD = CREATURE_ORC_SLAYER
CREATURE_DWARF_WARRIOR = CREATURE_ORC_WARMONGER

-- lvl 5
CREATURE_FASCINATOR = CREATURE_SHAMAN
CREATURE_DWARF_ADEPT = CREATURE_SHAMAN_WITCH
CREATURE_WARLOCK = CREATURE_SHAMAN_HAG

-- lvl 1
CREATURE_TROGLODYTE = CREATURE_ORCHIEF_BUTCHER
CREATURE_CHTONIC = CREATURE_ORCHIEF_EXECUTIONER
CREATURE_INFERNAL_TROGLODYTE = CREATURE_ORCHIEF_CHIEFTAIN

-- lvl 7
CREATURE_COLOSSUS = CREATURE_CYCLOP
CREATURE_DWARVEN_GOLEM = CREATURE_CYCLOP_UNTAMED
CREATURE_TITAN_GENERATOR = CREATURE_CYCLOP_BLOODEYED

-- lvl 6
CREATURE_MANTICORE = 2109
CREATURE_DARK_MANTICORE = 2110
CREATURE_ACID_MANTICORE = 2111