---@alias ArtifactBlankType
---|`ARTIFACT_PRIMARY_WEAPON_BLANK`
---|`ARTIFACT_SECONDARY_WEAPON_BLANK`
---|`ARTIFACT_ARMOR_BLANK`
---|`ARTIFACT_HELMET_BLANK`
---|`ARTIFACT_BOOTS_BLANK`
---|`ARTIFACT_RING_BLANK`
---|`ARTIFACT_NECLACE_BLANK`
---|`ARTIFACT_CLOAK_BLANK`
---|`ARTIFACT_POCKET_BLANK`
ARTIFACT_PRIMARY_WEAPON_BLANK = 175
ARTIFACT_SECONDARY_WEAPON_BLANK = 176
ARTIFACT_ARMOR_BLANK = 177
ARTIFACT_HELMET_BLANK = 178
ARTIFACT_BOOTS_BLANK = 179
ARTIFACT_RING_BLANK = 180
ARTIFACT_NECLACE_BLANK = 181
ARTIFACT_CLOAK_BLANK = 182
ARTIFACT_POCKET_BLANK = 183

---@alias ArtifactInsigniaType
---|`ARTIFACT_INSIGNIA_OF_POWER`
---|`ARTIFACT_INSIGNIA_OF_PROTECTION`
---|`ARTIFACT_INSIGNIA_OF_WIZARDY`
---|`ARTIFACT_INSIGNIA_OF_ENLIGHTMENT`
---|`ARTIFACT_INSIGNIA_OF_HASTE`
---|`ARTIFACT_INSIGNIA_OF_SWIFTNESS`
---|`ARTIFACT_INSIGNIA_OF_VITALITY`
---|`ARTIFACT_INSIGNIA_OF_FORTUNE`
---|`ARTIFACT_INSIGNIA_OF_COURAGE`
ARTIFACT_INSIGNIA_OF_POWER = 184
ARTIFACT_INSIGNIA_OF_PROTECTION = 185
ARTIFACT_INSIGNIA_OF_WIZARDY = 186
ARTIFACT_INSIGNIA_OF_ENLIGHTMENT = 187
ARTIFACT_INSIGNIA_OF_HASTE = 188
ARTIFACT_INSIGNIA_OF_SWIFTNESS = 189
ARTIFACT_INSIGNIA_OF_VITALITY = 190
ARTIFACT_INSIGNIA_OF_FORTUNE = 191
ARTIFACT_INISGNIA_OF_COURAGE = 192

---@alias ArtifactSealType 
---|`ARTIFACT_SEAL_OF_MIGHT`
---|`ARTIFACT_SEAL_OF_MAGIC`
ARTIFACT_SEAL_OF_MIGHT = 193
ARTIFACT_SEAL_OF_MAGIC = 194

---@alias ArtifactEnchantmentType
---|`ARTIFACT_SIGIL_OF_STEPPE`
---|`ARTIFACT_SIGIL_OF_BLOOM`
---|`ARTIFACT_SIGIL_OF_CALMNESS`
---|`ARTIFACT_SIGIL_OF_DEATH`
---|`ARTIFACT_SIGIL_OF_BURNING_HEART`
---|`ARTIFACT_SIGIL_OF_LIGHT`
---|`ARTIFACT_SIGIL_OF_PROGRESS`
---|`ARTIFACT_SIGIL_OF_RAGE`
---|`ARTIFACT_SIGIL_OF_DRAGONS`
ARTIFACT_SIGIL_OF_STEPPE = 195
ARTIFACT_SIGIL_OF_BLOOM = 196
ARTIFACT_SIGIL_OF_CALMNESS = 197
ARTIFACT_SIGIL_OF_DEATH = 198
ARTIFACT_SIGIL_OF_BURNING_HEART = 199
ARTIFACT_SIGIL_OF_LIGHT = 200
ARTIFACT_SIGIL_OF_PROGRESS = 201
ARTIFACT_SIGIL_OF_RAGE = 202
ARTIFACT_SIGIL_OF_DRAGONS = 203