consoleCmd('console_size 10000')
doFile('/scripts/3rdparty/lualib.lua')
doFile("/scripts/common/global/consts.lua")
doFile("/scripts/common/random.lua")
sleep()
doFile("/scripts/entity/creature/abils.lua")
doFile("/scripts/entity/creature/consts.lua")
doFile("/scripts/entity/artifact/consts.lua")
doFile("/scripts/entity/hero/consts.lua")
doFile("/scripts/entity/spell/consts.lua")
sleep()
while not HERO_SPEC_NONE and TOWN_NO_TYPE do
	sleep()
end
doFile('/scripts/lib/creatures_table.lua')
doFile('/scripts/lib/heroes_info.lua')
doFile('/scripts/lib/spells_info.lua')
doFile("/scripts/lib/arts_info.lua")
sleep()
doFile("/scripts/entity/load.lua")
sleep()
doFile("/scripts/common/combat/override.lua")
doFile("/scripts/common/combat/misc.lua")