---@alias NewBuildingType
---|`BUILDING_TYPE_WEAPONSMITH`
---|`BUILDING_TYPE_ARMORSMITH`
---|`BUILDING_TYPE_JEWELRY`
BUILDING_TYPE_WEAPONSMITH = 0
BUILDING_TYPE_ARMORSMITH = 1
BUILDING_TYPE_JEWELRY = 2