NEW_BUILDINGS_DATA = {
	["BUILDING_TYPE_WEAPONSMITH_1"] = BUILDING_TYPE_WEAPONSMITH,
	["BUILDING_TYPE_WEAPONSMITH_2"] = BUILDING_TYPE_WEAPONSMITH,
	["BUILDING_TYPE_ARMORSMITH_1"] = BUILDING_TYPE_ARMORSMITH,
	["BUILDING_TYPE_ARMORSMITH_2"] = BUILDING_TYPE_ARMORSMITH,
}

NEW_BANKS_DATA = {
	["BTD_BANK_CRYPT_1"] = BTD_BANK_CRYPT,
}