MiniDialog.Sets["C2M1_DIALOG_02"] = {
	["0_main"] = {speaker = "Noellie", speaker_type = SPEAKER_TYPE_HERO},
	["1_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["2_main"] = {speaker = "Noellie", speaker_type = SPEAKER_TYPE_HERO},
	["3_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["4_main"] = {speaker = "Noellie", speaker_type = SPEAKER_TYPE_HERO},
	["5_main"] = {speaker = 2192, speaker_type = SPEAKER_TYPE_CREATURE},
	["6_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["7_main"] = {speaker = 2192, speaker_type = SPEAKER_TYPE_CREATURE},
	["8_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["9_main"] = {speaker = 2192, speaker_type = SPEAKER_TYPE_CREATURE},
	["10_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["11_main"] = {speaker = 2192, speaker_type = SPEAKER_TYPE_CREATURE},
	["12_main"] = {speaker = "Noellie", speaker_type = SPEAKER_TYPE_HERO},
	["13_main"] = {speaker = 2192, speaker_type = SPEAKER_TYPE_CREATURE},
	["14_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["15_main"] = {speaker = 2192, speaker_type = SPEAKER_TYPE_CREATURE},
	["16_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["17_main"] = {speaker = "Noellie", speaker_type = SPEAKER_TYPE_HERO},
	["18_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
	["19_main"] = {speaker = "Noellie", speaker_type = SPEAKER_TYPE_HERO},
	["20_main"] = {speaker = "Karlam", speaker_type = SPEAKER_TYPE_HERO},
}

